### ISSUE TITLE
Problems running tutorial in google vm

### ISSUE THREAD

**Issue by drencrom** [antongisli/maas-baremetal-k8s-tutorial#1]
Hi, I tried the tutorial in a new google vm but it failed. I tested using ubuntu bionic and focal but both return different errors.

### Bionic:

* The lxd snap is not installed so doing switch and refresh returns an error. It has to be manually installed first.
* When running `lxd init` it returns this error: `Error: Failed to create storage pool 'default': The "zfs" tool is not enabled`

### Focal:

* When running `maas admin vm-host compose` returns this error: `Unable to compose machine because: Failed talking to pod: Failed creating instance record: Instance type "virtual-machine" is not supported on this server`

In both cases it would be useful to run `apt update` before installing iptables-persistent in case it is a newly installed system.

**Comment by antongisli** [comment]
Hi - thanks for this report. 

The tutorial is not tested on bionic, so I will explicitly state it should be focal or higher.

You might be getting the error you have on focal because  you are not using a bare metal machine to start with, i.e you're trying to nest VMs twice. The tutorial assumes you are using an actual machine.

If this answers your questions let me know and I'll close the issue after updating the readme/docs.
